### ISSUE TITLE
Add alloc feature and make it optional

### ISSUE THREAD

**Issue by jasta** [jasta/ble-peripheral#1]
These traits don't _really_ depend on alloc, but a few of the descriptor types (Advertisement and GattService/Characteristic/Descriptor) need data structures and these are pretty awkward to implement with const generics and for seemingly little benefit given that this usage of alloc can be used downstream at app initialization only.

**Comment by jasta** [comment]
Found a better way thanks to @ivmarkov: https://github.com/jasta/ble-peripheral/commit/348fe45ee8d97318980f179d110d13fe4ac8145f

**Comment by ivmarkov** [comment]
@jasta I would like to put a few extra comments / feedback, but it is kind of difficult to do without an opened PR. Any brilliant ideas?

**Comment by jasta** [comment]
Maybe just link to the lines directly and comment?  I can open PRs from here on, just was direct pushing to move fast during the very early stages :)

**Comment by jasta** [comment]
GitHub got confused about your earlier comment on a commit as well, but I totally reworked how Advertisement works and don't need alloc there either.  I'm still mildly confused as to why Rust allows this unowned slice magic for arrays but nothing else, a mystery for another day perhaps :)

**Comment by ivmarkov** [comment]
> Maybe just link to the lines directly and comment? I can open PRs from here on, just was direct pushing to move fast during the very early stages :)

Sounds like a lot of work :) Can you somehow open a PR against *something*? I really want to provide feedback for a few things :)

**Comment by ivmarkov** [comment]
As in against an empty branch in your repo?

**Comment by jasta** [comment]
Oh I see, you've got a lot to say about it :stuck_out_tongue:   Here you go: https://github.com/jasta/ble-peripheral/pull/4
